### ISSUE TITLE
duplicate property name 'title'?

### ISSUE THREAD

**Issue by thearabbit** [RainHaven/iron-seo#1]
I used `breadcrumbs` package that use `title` property to set name, so it duplication with this.
how to solve.

**Comment by scottmcpherson** [comment]
Hey @yuomtheara. I've never used the breadcrumbs package. Does the title property also set the html title in the breadcrumbs package?

The two solutions that come to mind are name spacing, and checking in iron-seo for the existence of the breadcrumbs package, and then deciding what to do with the title from there.

**Comment by thearabbit** [comment]
excuse me, could example?

**Comment by scottmcpherson** [comment]
The solutions that I offered aren't added into the package yet. I'll need to think about best solution here and possibly add it in.

**Comment by thearabbit** [comment]
Now I remove the `breadcrumbs` and use this.
